openapi: 3.0.3
info:
  title: Swagger Productos - OpenAPI 3.0
  description: |-
    This specification can help you learn more about the Product API.
  contact:
    email: roberto_sh_17@hotmail.com
  version: 0.0.1
servers:
  - url: localhost:8080/api/v1
tags:
  - name: Products
    description: Everything about products
  - name: Categories
    description: Everything about products
paths:
  /products:
    post:
      tags:
        - Products
      summary: Add a new product to the store
      description: Add a new product to the store
      operationId: addProduct
      requestBody:
        description: Create a new product in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductIn'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponsePost'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /products/{productCode}:
    get:
      tags:
        - Products
      summary:  Find prodcut by code
      description: Find prodcut by code
      operationId: findProduct
      parameters:
        - name: productCode
          in: path
          description: Code of product to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductOut'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
    put:
      tags:
        - Products
      summary: Update a product to the store
      description: Update a product to the store
      operationId: updateProduct
      parameters:
        - name: productCode
          in: path
          description: Code of product to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update a product to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductIn'
        required: true
      responses:
        '204':
          description: Successful operation
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /categories:
    post:
      tags:
        - Categories
      summary: Add a new category to the store
      description: Add a new category to the store
      operationId: addCategory
      requestBody:
        description: Create a new category in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryIn'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryOutPost'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /categories/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: Find category by id
          required: true
          schema:
            type: integer
            format: int64
      tags:
        - Categories
      summary: Add a new category to the store
      description: Add a new category to the store
      operationId: findCategory
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryOut'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
components:
  schemas:
    ProductOut:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
          description: Product id
        employeeId:
          type: integer
          format: int64
          example: 10
          description: Employe id
        productType:
          type: string
          example: standard
        name:
          type: string
          example: Petalo 8 rollos
        code:
          type: integer
          example: 06502550
          description: Product code
        categoryId:
          type: string
          example: aec96f3b-ec3d-42b0-91bd-c680c44a123a
        supplierId:
          type: string
          example: aec96f3b-ec3d-42b0-91bd-c680c44a123a
        brandId:
          type: string
          example: aec96f3b-ec3d-42b0-91bd-c680c44a123a
        barcodeType:
          type: string
          example: code128
        boxId:
          type: string
          example: common box
        unitId:
          type: string
          example: piezas
        price:
          type: number
          example: 30.65
        stockAlert:
          type: integer
          example: 5
          description: Minimum stock to send alert to the administrator
        description:
          type: string
          example: Papel higienico marca petalo.
          description: Product description
        status:
          type: boolean
          example: true
          description: Product status
        percentageTax:
          type: boolean
          example: 18
          description: Percentage of purchase taxes.
        methodTax:
          type: boolean
          example: INCLUSIVO
    ProductIn:
      required:
        - employeeId
        - productType
        - name
        - code
        - categoryId
        - supplierId
        - brandId
        - barcodeType
        - boxId
        - unitId
        - price
      type: object
      properties:
        employeeId:
          type: integer
          format: int64
          example: 10
          description: Employe id
        productType:
          type: string
          example: standard
        name:
          type: string
          example: Petalo 8 rollos
        code:
          type: integer
          example: 06502550
          description: Product id
        categoryId:
          type: string
          example: aec96f3b-ec3d-42b0-91bd-c680c44a123a
        supplierId:
          type: string
          example: aec96f3b-ec3d-42b0-91bd-c680c44a123a
        brandId:
          type: string
          example: aec96f3b-ec3d-42b0-91bd-c680c44a123a
        barcodeType:
          type: string
          example: code128
        boxId:
          type: string
          example: common box
        unitId:
          type: string
          example: piezas
        price:
          type: number
          example: 30.65
        stockAlert:
          type: integer
          example: 5
          description: Minimum stock to send alert to the administrator
        description:
          type: string
          example: Papel higienico marca petalo.
          description: Product description
        status:
          type: boolean
          example: true
          description: Product status
        percentageTax:
          type: boolean
          example: 18
          description: Percentage of purchase taxes.
        methodTax:
          type: boolean
          example: INCLUSIVO
    CategoryIn:
      required:
        - name
        - boxId
      type: object
      properties:
        name:
          type: string
          example: Higiene bucal
        fatherCategory:
          type: string
          example: higiene
          description: Hierarchically higher category
        boxId:
          type: string
          example: common box
        description:
          type: string
          example: Categoria para productos de higiene bucal.
          description: Category description
        status:
          type: boolean
          example: true
          description: Category status
    CategoryOutPost:
      type: object
      properties:
        id:
          type: integer
          example: 26
    CategoryOut:
      type: object
      properties:
        id:
          type: integer
          example: 26
        name:
          type: string
          example: Higiene bucal
        fatherCategory:
          type: string
          example: higiene
          description: Hierarchically higher category
        boxId:
          type: string
          example: common box
        description:
          type: string
          example: Categoria para productos de higiene bucal.
          description: Category description
        status:
          type: boolean
          example: true
          description: Category status
    ProductResponsePost:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 10
        code:
          type: integer
          format: int32
          example: 6502550
    GenericResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 10

  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header